module.exports = [
  {
    name: 'Labore et Dolore',
    picture: './dist/img/person1.png',
    verified: 'one',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'Developer',
    industry: 'Software Development',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, German',
    price: '$200',
  },
  {
    name: 'Magna Aliqua',
    picture: './dist/img/person2.jpg',
    verified: 'two',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '5',
    title: 'Sales Manager',
    industry: 'Sales',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, German',
    price: '$230',
  },
  {
    name: 'Euismod Tempor',
    picture: './dist/img/person3.jpg',
    verified: 'three',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '1',
    title: 'Developer',
    industry: 'Software Development',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, French, German',
    price: '$250',
  },
  {
    name: 'Dolor Amet',
    picture: './dist/img/person4.jpg',
    verified: 'four',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '0',
    title: 'Tester',
    industry: 'Software Testing',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, French, German',
    price: '$270',
  },
  {
    name: 'Quis Nostrud',
    picture: './dist/img/person5.jpg',
    verified: 'five',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '5',
    title: 'Developer',
    industry: 'Software Development',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, Polish',
    price: '$250',
  },
  {
    name: 'Incididunt Enim',
    picture: './dist/img/person1.png',
    verified: 'six',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '3',
    title: 'Tester',
    industry: 'Software Testing',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, Polish',
    price: '$270',
  },
  {
    name: 'Minim Veniam',
    picture: './dist/img/person2.jpg',
    verified: 'seven',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '4',
    title: 'Developer',
    industry: 'Software Development',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, Polish',
    price: '$250',
  },
  {
    name: 'Ullamco Minim',
    picture: './dist/img/person3.jpg',
    verified: 'eight',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'Tester',
    industry: 'Software Testing',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, German',
    price: '$250',
  },
  {
    name: 'Lorem Ipsum',
    picture: './dist/img/person4.jpg',
    verified: 'nine',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '0',
    title: 'Developer',
    industry: 'Software Development',
    destination: 'Remote',
    salary: '12000',
    availability: 'next month',
    languages: 'English, German',
    price: '$200',
  }
]
